const express = require( 'express' )
const path = require( 'path' )
const ejs = require( 'ejs' )
const app = express()
const server = require( 'http' ).createServer( app )
const createIo = require( 'socket.io' )

const EmittableError = require( './src/models/EmittableError' )
const { getTestHandler } = require( './src/handlers/testHandler' )

process.env.EVENT_NAME = 'default'
const PORT = process.env.PORT || 3000

app.use( express.static( path.join( __dirname, 'public' ) ) )
app.set( 'views', path.join( __dirname, 'public' ) )
app.engine( 'html', ejs.renderFile )
app.set( 'view engine', 'html' )

app.use( '/', ( req, res ) => {
  res.render( 'index.html' )
} )

// TO DO: make sure the room is removed after all participants have left the room
const ROOMS = []

const generateId = ( () => {
  let id = 0
  return () => id++
} )()

const io = createIo( server, {
  cors: {
    origin: '*',
    credentials: true
  },
  allowEIO3: true
} )

io.on( 'connection', socket => {
  console.log( 'Connected socket: ', socket.id )

  socket.on( 'create_a_room', ( message ) => {
    const { roomName, username } = message
    const roomId = generateId()
    ROOMS[ roomId ] = {}
    ROOMS[ roomId ].name = roomName
    ROOMS[ roomId ].owner = username

    console.log( `Room ${ ROOMS[ roomId ].name } with id ${ roomId } created by ${ username }.` )
  } )

  socket.on( 'join_a_room', ( roomName ) => {
    console.log( `Trying to locate room ${ roomName }...` )
    const roomExists = ROOMS.find( room => room.name === roomName )
    if ( roomExists ) {
      console.log( 'Room found. Joining room.' )
      socket.join( roomName )
    } else {
      console.error( 'Room not found.' )
      socket.emit( 'error', new EmittableError( "The room you are trying to access doesn't exists" ) )
    }
  } )

  socket.on( 'leave_the_room', ( roomName ) => {
    console.log( `Leaving room ${ roomName }...` )
    socket.leave( roomName )
  } )

  // ********************* Autogenerated events **************************

  io.of('/').adapter.on( 'join-room', ( room, socketId ) => {
    console.log( `socket ${ socketId } has joined room ${room}` )
  } )

  io.of('/').adapter.on( 'leave-room', ( room, socketId ) => {
    console.log( `socket ${ socketId } left the room ${room}` )
  } )
// ***********************************************************************

  socket.on( 'error', ( error ) => {
    console.error( error.message )
  } )

  socket.on( 'test', () => {
  try {
    throw new Error( 'cagando de proposito' )
  } catch ( error ) {
    console.error( error.stack )
    socket.emit( 'error', new EmittableError( error ) )
  }
  }  /*getTestHandler( socket )*/ )
} )

server.listen( PORT, () => console.log( `Server running on port ${ PORT }` ) )
